[package]
name = "country_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
ddsfile = "0.5.2"
image_dds = "0.5.1"
rocket = { version = "0.5.1", features = ["json"]}
serde_json = "1.0.117"
serde_yaml = "0.9.34"
vic3-parser = { path = "../parser" }
